name: create gh-pages

on:
  workflow_run:
    workflows: ["build and test"]
    branches: [ main ]
    types:
      - completed
      
jobs: 
  create-gh-pages:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
      
      - uses: langroodi/doxygenize@v1
        with: 
          darkmode: true
